#!/usr/bin/env python3
import rospy
from std_msgs.msg import Float32MultiArray
from std_msgs.msg import Int16MultiArray
from sensor_msgs.msg import Joy
from drive_control.arm import Arm

class ArmController(object):
    
    def __init__(self):
        self.arm = Arm()
        self.topics = rospy.get_param("/topics")
        rospy.Subscriber(self.topics["arm_in"], Float32MultiArray, self.arm_callback)
        rospy.Subscriber(self.topics["is_on"], Int16MultiArray, self.is_on_callback)
        rospy.Subscriber(self.topics["joy"], Joy, self.joy_callback)
        self.arm_pub = rospy.Publisher(self.topics["arm_out"], Float32MultiArray, queue_size=10)

        self.is_teleop = False
    
    def arm_callback(self, data):
        # float32 array with angle values
        return  # disabled for testing
        self.arm.set_pos(data.data)

    def is_on_callback(self, data):
        self.is_teleop = data.data[0]
    
    def joy_callback(self, data):
        if not self.is_teleop:
            return
        # Go to setpoint
        if data.buttons[0] == 1:    # X
            # up
            self.arm.set_pos((400, 415, 500, 480, 500, 500))
        elif data.buttons[1]:       # O
            # link 1 up, link 2 bent (pointing forward)
            self.arm.set_pos((400, 415, 500, 480, 800, 500))
        elif data.buttons[2]:       # Triangle
            # arm up
            self.arm.set_pos((400, 415, 500, 880, 650, 500))
        elif data.buttons[3]:       # Square
            self.arm.set_pos((400, 415, 500, 150, 650, 500))       

    def pub_arm_pos(self):
        self.arm_pub.publish(Float32MultiArray(self.arm.get_pos()))

if __name__ == "__main__":
    rospy.init_node("arm_control")

    arm_controller = ArmController()

    rospy.loginfo("Arm node started AAAAAAAAAAAAAAAAAAAA")
    rospy.spin()