#!/usr/bin/env python3
import rospy
from drive_control.encoder import Encoder

class EncoderReader(object):

    def __init__(self):
        self.left_enc = Encoder(20, 21)
        self.right_enc = Encoder(16, 26)

        self.ticks_pub = rospy.Publisher("/yeah")