#!/usr/bin/env python3
import rospy
import numpy as np
from drive_control.motor import Motor
from std_msgs.msg import String
from std_msgs.msg import Int16MultiArray
from sensor_msgs.msg import Joy
from nav_msgs.msg import Odometry

class MotorController(object):

    def __init__(self):
        pins = rospy.get_param("/pins")
        topics = rospy.get_param("/topics")
        hz = 100

        self.left_motor = Motor(pins["pwm"]["left"], pins["dir"]["left"], hz, False)
        self.right_motor = Motor(pins["pwm"]["right"], pins["dir"]["right"], hz, False)

        self.drive_pub = rospy.Publisher(topics["drive_out"], String, queue_size=10)
        self.cmplt_pub = rospy.Publisher(topics["cmd_cmplt"], String, queue_size=3)
        rospy.Subscriber(topics["drive_in"], String, self.drive_callback)
        rospy.Subscriber(topics["is_on"], Int16MultiArray, self.is_on_callback)
        rospy.Subscriber(topics["joy"], Joy, self.joy_callback)

        self.is_teleop = False
    
    def drive_callback(self, data):
        
        return  # auto commands

    def is_on_callback(self, data):
        self.is_teleop = data.data[0]
    
    def joy_callback(self, data):
        if not self.is_teleop:
            return
        
        self.left_motor.set_vel(data.axes[1])
        self.right_motor.set_vel(data.axes[4])

        self.drive_pub.publish(String("Left: " + str(data.axes[1]) + "   Right: " + str(data.axes[4])))
    
    def align_on_stairs(self):
        # assumes pointed directly at the stairs, at its base
        return  # 

    def drive_pid(self, vels):  # vels is a tuple with left and right vel in m/s
        return # publish to l/rwheel_vtarget
        # also make the publisher, subscriber, and callback function

    def stop(self):
        self.left_motor.stop()
        self.right_motor.stop()

if __name__ == "__main__":
    rospy.init_node("motor_control")

    motor_controller = MotorController()

    rospy.on_shutdown(motor_controller.stop)
    rospy.loginfo("Motor controller node started")
    rospy.spin()