// Generated by gencpp from file drive_control/OutputState.msg
// DO NOT EDIT!


#ifndef DRIVE_CONTROL_MESSAGE_OUTPUTSTATE_H
#define DRIVE_CONTROL_MESSAGE_OUTPUTSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drive_control
{
template <class ContainerAllocator>
struct OutputState_
{
  typedef OutputState_<ContainerAllocator> Type;

  OutputState_()
    : state(false)
    , duration(0)  {
    }
  OutputState_(const ContainerAllocator& _alloc)
    : state(false)
    , duration(0)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;

   typedef uint8_t _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::drive_control::OutputState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drive_control::OutputState_<ContainerAllocator> const> ConstPtr;

}; // struct OutputState_

typedef ::drive_control::OutputState_<std::allocator<void> > OutputState;

typedef boost::shared_ptr< ::drive_control::OutputState > OutputStatePtr;
typedef boost::shared_ptr< ::drive_control::OutputState const> OutputStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drive_control::OutputState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drive_control::OutputState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drive_control::OutputState_<ContainerAllocator1> & lhs, const ::drive_control::OutputState_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drive_control::OutputState_<ContainerAllocator1> & lhs, const ::drive_control::OutputState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drive_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::drive_control::OutputState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drive_control::OutputState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drive_control::OutputState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drive_control::OutputState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drive_control::OutputState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drive_control::OutputState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drive_control::OutputState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e48107ec9af92b61adf575e5d66914d0";
  }

  static const char* value(const ::drive_control::OutputState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe48107ec9af92b61ULL;
  static const uint64_t static_value2 = 0xadf575e5d66914d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::drive_control::OutputState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drive_control/OutputState";
  }

  static const char* value(const ::drive_control::OutputState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drive_control::OutputState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# set the pin to high or low via true/false\n"
"bool state\n"
"\n"
"# Optionally, provide duration for state. <= 0 will leave in state indefinitely.\n"
"uint8 duration\n"
;
  }

  static const char* value(const ::drive_control::OutputState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drive_control::OutputState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OutputState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drive_control::OutputState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drive_control::OutputState_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "duration: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRIVE_CONTROL_MESSAGE_OUTPUTSTATE_H
